apiVersion: v1
kind: Service
metadata:
  name: generator
  labels:
    app: generator
spec:
  # If you are running k8s on a local dev box, using minikube, or Kubernetes on docker desktop you can use type NodePort instead
  type: LoadBalancer
  ports:
  - port: 8384
    targetPort: 8384
  selector:
    app: generator
